---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-app
  namespace: prod
  labels:
    app: public-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
        - name: public-app
          image: hari1se/backend-app:v1.0.3
          ports:
            - containerPort: 8000
